[project]
name = "ai-challenge"
version = "0.1.0"
description = "Qualification stage of AI Challenge: tasks solving training"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dask>=2025.9.0",
    "lightgbm>=4.6.0",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
]
